---
# tasks file for sbaerlocher.traefik

- name: create traefik network
  docker_network:
    name: "{{ traefik_network }}"
    ipam_options:
      subnet: '172.16.1.0/24'
      gateway: '172.16.1.1'
      iprange: '172.16.1.0/24'
  tags:
    - configuration

- name: create traefik directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: docker
    mode: 0550
  with_items:
    - /etc/traefik
  tags:
    - configuration

- name: configuration traefik
  template:
    src: "traefik.toml.j2"
    dest: "/etc/traefik/traefik.toml"
    owner: root
    group: docker
    mode: 0550
  notify:
    - restart proxy_1
  tags:
    - configuration

- name: start traefik
  docker_container:
    name: proxy_1
    image: traefik
    restart_policy: unless-stopped
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/etc/traefik
    capabilities:
      - net_bind_service
    networks:
      - name: "{{ traefik_network }}"
  tags:
    - configuration
